export const LOADING = 'LOADING';

export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS';
export const CREATE_USER_ACCOUNT_ERROR = 'CREATE_USER_ACCOUNT_ERROR';

//Reset Reducer
export const RESET_AUTH = 'RESET_AUTH';
